const SMALL_ITEMS = [
  { name: "Electric kettle", brand: "Hamilton Beach", description: "A compact stainless-steel electric kettle.", price: 55, image: "https://images.unsplash.com/photo-1594213114663-d94db9b17125?auto=format&fit=crop&w=600&q=80" },
  { name: "Personal blender", brand: "Ninja", description: "A personal blender with two travel cups.", price: 79, image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=600&q=80" },
  { name: "Desk lamp", brand: "Globe Electric", description: "An adjustable LED task lamp.", price: 32, image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80" },
  { name: "Bluetooth speaker", brand: "JBL", description: "A portable water-resistant wireless speaker.", price: 74, image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80" },
  { name: "Toaster", brand: "Black+Decker", description: "A two-slice extra-wide-slot toaster.", price: 46, image: "https://images.unsplash.com/photo-1583722799618-179f37a8b80d?auto=format&fit=crop&w=600&q=80" },
  { name: "Hair dryer", brand: "Conair", description: "A lightweight ionic hair dryer.", price: 38, image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=600&q=80" },
  { name: "Waffle maker", brand: "Cuisinart", description: "A round non-stick waffle maker.", price: 67, image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=600&q=80" },
  { name: "Digital scale", brand: "Starfrit", description: "A glass-top digital kitchen scale.", price: 29, image: "https://images.unsplash.com/photo-1591261730799-ee4e6c2d16d7?auto=format&fit=crop&w=600&q=80" },
  { name: "French press", brand: "Bodum", description: "An eight-cup glass coffee press.", price: 42, image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80" },
  { name: "Milk frother", brand: "Nespresso", description: "A compact electric milk frother.", price: 89, image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=600&q=80" },
  { name: "Rice cooker", brand: "Black+Decker", description: "A six-cup automatic rice cooker.", price: 58, image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=600&q=80" },
  { name: "Hand mixer", brand: "KitchenAid", description: "A five-speed electric hand mixer.", price: 75, image: "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?auto=format&fit=crop&w=600&q=80" },
  { name: "Popcorn maker", brand: "Dash", description: "A hot-air countertop popcorn maker.", price: 39, image: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=600&q=80" },
  { name: "Coffee grinder", brand: "Braun", description: "A stainless-steel blade coffee grinder.", price: 36, image: "https://images.unsplash.com/photo-1520171285021-e1bb1d1c0e20?auto=format&fit=crop&w=600&q=80" },
  { name: "Alarm clock", brand: "Sony", description: "A digital AM/FM clock radio.", price: 31, image: "https://images.unsplash.com/photo-1501139083538-0139583c060f?auto=format&fit=crop&w=600&q=80" },
  { name: "Headphones", brand: "Skullcandy", description: "Wireless over-ear headphones.", price: 69, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80" },
  { name: "Computer mouse", brand: "Logitech", description: "A rechargeable wireless computer mouse.", price: 54, image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80" },
  { name: "Portable charger", brand: "Belkin", description: "A ten-thousand milliamp-hour power bank.", price: 47, image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=600&q=80" },
  { name: "Electric toothbrush", brand: "Oral-B", description: "A rechargeable electric toothbrush.", price: 83, image: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=600&q=80" },
  { name: "Beard trimmer", brand: "Philips", description: "A cordless beard and hair trimmer.", price: 57, image: "https://images.unsplash.com/photo-1621607512022-6aecc4fed814?auto=format&fit=crop&w=600&q=80" },
  { name: "Heating pad", brand: "Sunbeam", description: "A soft electric heating pad.", price: 35, image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=600&q=80" },
  { name: "Garment steamer", brand: "Rowenta", description: "A handheld fabric steamer.", price: 72, image: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=600&q=80" },
  { name: "Yoga mat", brand: "Gaiam", description: "A cushioned non-slip exercise mat.", price: 34, image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=600&q=80" },
  { name: "Dumbbell set", brand: "CAP", description: "A pair of neoprene hand weights.", price: 48, image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80" },
  { name: "Camping lantern", brand: "Coleman", description: "A rechargeable outdoor lantern.", price: 41, image: "https://images.unsplash.com/photo-1504851149312-7a075b496cc7?auto=format&fit=crop&w=600&q=80" },
  { name: "Binoculars", brand: "Bushnell", description: "Compact all-purpose binoculars.", price: 86, image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80" },
  { name: "Tool set", brand: "Stanley", description: "A thirty-eight-piece household tool kit.", price: 78, image: "https://images.unsplash.com/photo-1581166397057-235af2b3c6dd?auto=format&fit=crop&w=600&q=80" },
  { name: "Garden pruner", brand: "Fiskars", description: "A geared bypass pruning shear.", price: 27, image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80" },
  { name: "Board game", brand: "Hasbro", description: "A family edition strategy board game.", price: 37, image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=600&q=80" },
  { name: "Instant camera", brand: "Fujifilm", description: "A colourful instant-print camera.", price: 94, image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80" },
  { name: "Air fryer", brand: "Instant", description: "A compact digital air fryer.", price: 96, image: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80" },
  { name: "Immersion blender", brand: "Braun", description: "A variable-speed hand blender.", price: 82, image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=600&q=80" },
  { name: "Electric skillet", brand: "Presto", description: "A family-size non-stick electric skillet.", price: 73, image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=600&q=80" },
  { name: "Label maker", brand: "Brother", description: "A handheld electronic label maker.", price: 51, image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=600&q=80" },
  { name: "Weather station", brand: "La Crosse", description: "A wireless colour home weather station.", price: 68, image: "https://images.unsplash.com/photo-1561553590-267fc716698a?auto=format&fit=crop&w=600&q=80" },
  { name: "Portable radio", brand: "Sangean", description: "A rechargeable AM/FM portable radio.", price: 62, image: "https://images.unsplash.com/photo-1593078165899-c7d2ac0d6aea?auto=format&fit=crop&w=600&q=80" },
  { name: "Electric blanket", brand: "Sunbeam", description: "A soft heated throw blanket.", price: 71, image: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&w=600&q=80" },
  { name: "Pressure washer", brand: "Ryobi", description: "A compact electric pressure washer.", price: 98, image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80" },
  { name: "Fire pit", brand: "Outland Living", description: "A portable propane outdoor fire pit.", price: 93, image: "https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=600&q=80" },
  { name: "Carry-on suitcase", brand: "Samsonite", description: "A lightweight hardside carry-on suitcase.", price: 91, image: "https://images.unsplash.com/photo-1553531384-cc64ac80f931?auto=format&fit=crop&w=600&q=80" },
];

// A broad rotating middle-price pool for the small-prize pricing games. These
// are deliberately spread across categories so a show is not dominated by
// countertop appliances. A used name is excluded for the rest of the show.
const EXTRA_SMALL_ITEMS = [
  ["Smart video doorbell","Google Nest",129,"A battery-powered doorbell with HD video.","tech"],["Mechanical keyboard","Logitech",119,"A compact wireless mechanical keyboard.","tech"],["Streaming media player","Apple",179,"A 4K streaming box with voice remote.","tech"],["Wi-Fi mesh router","TP-Link",149,"A dual-band whole-home Wi-Fi system.","tech"],["Portable photo printer","Canon",139,"A compact wireless colour photo printer.","tech"],["Fitness tracker","Fitbit",159,"A slim activity and sleep tracker.","tech"],["Smart speaker","Amazon Echo",89,"A voice-controlled home speaker.","tech"],["Webcam","Logitech",109,"A full-HD webcam with stereo microphones.","tech"],["Gaming headset","HyperX",99,"A comfortable wired gaming headset.","tech"],["Tablet stylus","Apple",129,"A precision stylus for drawing and notes.","tech"],
  ["Carry-on duffel","Roots",138,"A durable Canadian travel duffel.","travel"],["Hiking daypack","Osprey",145,"A ventilated daypack for trail adventures.","travel"],["Packing cube set","Monos",85,"A six-piece set of travel organizers.","travel"],["Travel pillow set","Cabeau",79,"A memory-foam neck pillow and travel kit.","travel"],["Picnic backpack","Outbound",99,"An insulated picnic pack fitted for four.","travel"],["Camping hammock","ENO",96,"A lightweight double camping hammock.","outdoors"],["Trekking poles","Black Diamond",139,"A pair of adjustable aluminum hiking poles.","outdoors"],["Cooler","Coleman",119,"A wheeled insulated outdoor cooler.","outdoors"],["Sleeping bag","Marmot",149,"A warm three-season sleeping bag.","outdoors"],["Portable camp stove","Eureka",129,"A compact two-burner propane stove.","outdoors"],
  ["Dutch oven","Le Creuset",399,"An enamelled cast-iron round Dutch oven.","cookware"],["Chef knife","Zwilling",149,"An eight-inch forged chef knife.","cookware"],["Cookware set","T-fal",189,"A ten-piece non-stick cookware collection.","cookware"],["Bamboo cutting board set","Paderno",79,"Three Canadian-designed bamboo boards.","cookware"],["Food storage set","Rubbermaid",69,"A twenty-piece airtight container set.","cookware"],["Roasting pan","Cuisinart",89,"A stainless-steel roaster with rack.","cookware"],["Cast-iron skillet set","Lodge",95,"Two pre-seasoned cast-iron skillets.","cookware"],["Knife block set","Henckels",229,"A fourteen-piece knife and block collection.","cookware"],["Bakeware set","Wilton",74,"A ten-piece non-stick baking set.","cookware"],["Bar tool collection","Rabbit",82,"A complete stainless-steel cocktail kit.","cookware"],
  ["Percale sheet set","Simons Maison",149,"A crisp cotton queen sheet set.","home"],["Weighted blanket","Hush",179,"A calming machine-washable weighted blanket.","home"],["Down-alternative duvet","QE Home",169,"A soft all-season queen duvet.","home"],["Bath towel collection","Hudson's Bay",118,"A coordinated set of plush cotton towels.","home"],["Table lamp pair","IKEA",99,"Two modern bedside table lamps.","home"],["Wall mirror","Umbra",150,"A large Canadian-designed decorative mirror.","home"],["Area rug","Ruggable",249,"A washable patterned accent rug.","home"],["Essential-oil diffuser","Saje",98,"An ultrasonic ceramic aroma diffuser.","home"],["Memory-foam pillows","Endy",170,"A pair of adjustable sleep pillows.","home"],["Entryway organizer","Umbra",135,"A modern wall mirror with storage hooks.","home"],
  ["Cordless drill kit","DeWalt",199,"A cordless drill, batteries, charger, and bag.","tools"],["Socket set","Mastercraft",149,"A professional one-hundred-piece socket set.","tools"],["Laser level","Bosch",129,"A self-levelling cross-line laser.","tools"],["Wet-dry vacuum","Ridgid",119,"A powerful compact shop vacuum.","tools"],["Stud finder kit","Franklin Sensors",89,"A wide electronic wall scanner and level.","tools"],["Oscillating multi-tool","Ryobi",139,"A cordless multi-tool with accessory blades.","tools"],["Work light","Milwaukee",99,"A rechargeable high-output LED work light.","tools"],["Tool backpack","Klein Tools",159,"A rugged organizer for hand tools.","tools"],["Digital multimeter","Klein Tools",109,"An auto-ranging electrical test meter.","tools"],["Step ladder","Gorilla Ladders",129,"A lightweight three-step household ladder.","tools"],
  ["Pickleball set","Selkirk",129,"Two paddles, balls, and a carrying case.","fitness"],["Adjustable kettlebell","Bowflex",199,"A space-saving adjustable training weight.","fitness"],["Foam roller kit","TriggerPoint",79,"A recovery roller and massage-ball set.","fitness"],["Resistance training kit","TRX",179,"A portable suspension-training system.","fitness"],["Badminton set","Yonex",99,"Four racquets, shuttlecocks, net, and case.","fitness"],["Basketball hoop","SKLZ",149,"An adjustable indoor arcade basketball hoop.","fitness"],["Golf putting mat","PuttOut",139,"A foldable home putting practice system.","fitness"],["Yoga bolster kit","Halfmoon",115,"A Canadian-made bolster, blocks, and strap.","fitness"],["Boxing glove set","Everlast",89,"Training gloves, wraps, and focus mitts.","fitness"],["Balance trainer","BOSU",179,"A full-size balance and strength trainer.","fitness"],
  ["Hair styling brush","Dyson",199,"A heated smoothing and volumizing brush.","personal"],["Electric shaver","Braun",169,"A rechargeable wet-and-dry foil shaver.","personal"],["Skin care collection","Clinique",124,"A complete cleansing and moisturizing routine.","personal"],["Manicure set","Revlon",79,"An electric manicure and pedicure system.","personal"],["Massage gun","Therabody",199,"A compact percussive muscle massager.","personal"],["Water flosser","Waterpik",109,"A countertop dental water flosser.","personal"],["Lighted makeup mirror","Conair",89,"A rechargeable magnifying vanity mirror.","personal"],["Fragrance collection","Sephora",145,"A discovery set with a full-size scent voucher.","personal"],["Heated foot spa","HoMedics",99,"A bubbling foot bath with heat and massage.","personal"],["Silk sleep set","Blissy",129,"A silk pillowcase, mask, and scrunchie set.","personal"],
  ["Acoustic guitar starter kit","Yamaha",249,"A full-size guitar with bag and accessories.","hobby"],["Instant-print camera kit","Fujifilm",159,"A colourful camera with film and album.","hobby"],["Deluxe art set","Faber-Castell",119,"A wooden case filled with artist materials.","hobby"],["Telescope","Celestron",189,"A portable beginner astronomical telescope.","hobby"],["Record player","Audio-Technica",199,"An automatic belt-drive turntable.","hobby"],["LEGO architecture set","LEGO",159,"A detailed landmark building collection.","hobby"],["Sewing machine","Brother",229,"A computerized machine with utility stitches.","hobby"],["Digital piano keyboard","Casio",219,"A portable sixty-one-key musical keyboard.","hobby"],["Board game library","Hasbro",99,"A collection of six classic family games.","hobby"],["Birdwatching kit","Nikon",179,"Binoculars, field guide, and carrying harness.","hobby"],
].map(([name,brand,price,description,category])=>({name,brand,price,description,category}));

const PRICING_SMALL_ITEMS=[...SMALL_ITEMS,...EXTRA_SMALL_ITEMS];

const GROCERIES = [
  { name: "Vanilla Ice Cream", brand: "Chapman's", description: "Four litres of Canadian-made vanilla ice cream.", price: 8.99, image: "https://www.chapmans.ca/wp-content/uploads/2022/11/Original-Vanilla-4L.png" },
  { name: "Maple Crème Cookies", brand: "Dare", description: "Canadian maple-leaf sandwich cookies with crème filling.", price: 4.49, image: "https://www.darefoods.com/wp-content/uploads/2021/03/Dare-Ultimate-Maple-Creme.png" },
  { name: "Cheezies", brand: "Hawkins", description: "A 210-gram bag of crunchy Canadian cheese snacks.", price: 4.29, image: "https://hawkinscheezies.com/wp-content/uploads/2020/08/cheezies-bag.png" },
  { name: "Coffee Crisp", brand: "Nestlé", description: "A four-pack of coffee-flavoured wafer bars.", price: 3.99, image: "https://www.madewithnestle.ca/sites/default/files/2024-02/coffee-crisp-4-pack.png" },
  { name: "Original Macaroni & Cheese", brand: "Kraft Dinner", description: "A 200-gram box of classic Canadian comfort food.", price: 2.19, image: "https://assets.kraftfoods.com/recipe_images/opendeploy/110084_640x428.jpg" },
  { name: "Ginger Ale", brand: "Canada Dry", description: "A twelve-pack of 355-millilitre cans.", price: 8.49, image: "https://www.canadadry.ca/images/product-ginger-ale.png" },
  { name: "All Dressed Chips", brand: "Ruffles", description: "A 200-gram bag of all-dressed potato chips.", price: 4.79, image: "https://www.tastyrewards.com/sites/default/files/2023-09/ruffles-all-dressed.png" },
  { name: "Maple Cookies", brand: "Leclerc", description: "Maple-leaf cookies made in Canada.", price: 3.49, image: "https://leclerc.ca/wp-content/uploads/2021/03/maple-leaf-cookies.png" },
  { name: "Ketchup Chips", brand: "Lay's", description: "A family-size bag of ketchup chips.", price: 4.99, image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80" },
  { name: "Peanut Butter", brand: "Kraft", description: "A jar of smooth peanut butter.", price: 7.49, image: "https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?auto=format&fit=crop&w=600&q=80" },
  { name: "Tomato Soup", brand: "Campbell's", description: "A can of condensed tomato soup.", price: 2.49, image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80" },
  { name: "Oat Cereal", brand: "Cheerios", description: "A family-size box of oat cereal.", price: 6.79, image: "https://images.unsplash.com/photo-1521483451569-e33803c0330c?auto=format&fit=crop&w=600&q=80" },
  { name: "Chocolate Milk", brand: "Neilson", description: "A two-litre carton of chocolate milk.", price: 5.29, image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80" },
  { name: "Greek Yogurt", brand: "Oikos", description: "A four-pack of vanilla Greek yogurt.", price: 5.99, image: "https://images.unsplash.com/photo-1571212515416-fca77afa66b3?auto=format&fit=crop&w=600&q=80" },
  { name: "Frozen Pizza", brand: "Dr. Oetker", description: "A thin-crust pepperoni pizza.", price: 6.49, image: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=600&q=80" },
  { name: "Orange Juice", brand: "Tropicana", description: "A bottle of pulp-free orange juice.", price: 6.99, image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=600&q=80" },
  { name: "Pasta Sauce", brand: "Classico", description: "A jar of tomato basil pasta sauce.", price: 4.79, image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=600&q=80" },
  { name: "Tortillas", brand: "Dempster's", description: "A package of flour tortillas.", price: 4.29, image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?auto=format&fit=crop&w=600&q=80" },
  { name: "Granola Bars", brand: "MadeGood", description: "A box of chocolate granola bars.", price: 5.49, image: "https://images.unsplash.com/photo-1621939514649-280e2aa9454f?auto=format&fit=crop&w=600&q=80" },
  { name: "Dish Soap", brand: "Sunlight", description: "A bottle of lemon dish soap.", price: 3.99, image: "https://images.unsplash.com/photo-1585832770485-e68a5dbfad52?auto=format&fit=crop&w=600&q=80" },
  { name: "Facial Tissues", brand: "Scotties", description: "A six-box package of facial tissues.", price: 9.49, image: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?auto=format&fit=crop&w=600&q=80" },
  { name: "Toothpaste", brand: "Crest", description: "A twin-pack of mint toothpaste.", price: 7.99, image: "https://images.unsplash.com/photo-1559591937-e6e7f1c2270c?auto=format&fit=crop&w=600&q=80" },
  { name: "Shampoo", brand: "Dove", description: "A bottle of daily moisture shampoo.", price: 6.49, image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=600&q=80" },
  { name: "Hand Soap", brand: "Softsoap", description: "A refill bottle of liquid hand soap.", price: 5.79, image: "https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?auto=format&fit=crop&w=600&q=80" },
  { name: "Laundry Detergent", brand: "Tide", description: "A bottle of liquid laundry detergent.", price: 9.99, image: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=600&q=80" },
  { name: "Apple Sauce", brand: "Mott's", description: "A six-pack of apple sauce cups.", price: 4.69, image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80" },
  { name: "Black Tea", brand: "Red Rose", description: "A box of orange pekoe tea bags.", price: 6.29, image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=600&q=80" },
  { name: "Pancake Mix", brand: "Pearl Milling", description: "A box of original pancake mix.", price: 4.99, image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=600&q=80" },
  { name: "Canned Tuna", brand: "Clover Leaf", description: "A can of flaked light tuna.", price: 2.79, image: "https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=600&q=80" },
  { name: "Yellow Mustard", brand: "French's", description: "A squeeze bottle of yellow mustard.", price: 3.49, image: "https://images.unsplash.com/photo-1528750717929-32abb73d3bd9?auto=format&fit=crop&w=600&q=80" },
  { name: "Root Beer", brand: "A&W", description: "A twelve-pack of root beer cans.", price: 8.99, image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80" },
  { name: "Potato Wedges", brand: "McCain", description: "A bag of frozen seasoned potato wedges.", price: 4.99, image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80" },
  { name: "Cream Cheese", brand: "Philadelphia", description: "A tub of original cream cheese.", price: 5.49, image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=80" },
  { name: "Baked Beans", brand: "Heinz", description: "A can of beans in tomato sauce.", price: 2.29, image: "https://images.unsplash.com/photo-1606851091851-e8c8c0fca5ba?auto=format&fit=crop&w=600&q=80" },
  { name: "Chocolate Cookies", brand: "Dad's", description: "A bag of classic oatmeal chocolate cookies.", price: 4.59, image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80" },
  { name: "Salsa", brand: "Tostitos", description: "A jar of medium chunky salsa.", price: 4.99, image: "https://images.unsplash.com/photo-1613514785940-daed07799d9b?auto=format&fit=crop&w=600&q=80" },
  { name: "Instant Coffee", brand: "Nescafé", description: "A jar of rich instant coffee.", price: 8.49, image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80" },
  { name: "Frozen Blueberries", brand: "PC", description: "A bag of Canadian wild blueberries.", price: 6.99, image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=600&q=80" },
  { name: "Paper Towels", brand: "SpongeTowels", description: "A six-roll package of paper towels.", price: 9.79, image: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?auto=format&fit=crop&w=600&q=80" },
  { name: "Mouthwash", brand: "Listerine", description: "A large bottle of antiseptic mouthwash.", price: 8.29, image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=600&q=80" },
];

const CARS = [
  { name: "2026 Hyundai Elantra Essential", brand: "Hyundai", description: "A compact sedan with an automatic transmission, heated front seats, and modern safety technology.", price: 26135, image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Toyota Corolla LE", brand: "Toyota", description: "A fuel-efficient sedan with automatic climate control and a touchscreen multimedia system.", price: 28164, image: "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Nissan Sentra S", brand: "Nissan", description: "A comfortable compact sedan with intelligent emergency braking and smartphone integration.", price: 25146, image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Honda Civic LX", brand: "Honda", description: "A refined compact sedan with heated seats and Honda Sensing safety technology.", price: 32156, image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Mazda3 GX", brand: "Mazda", description: "A stylish compact sedan with responsive handling and smartphone connectivity.", price: 31246, image: "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Kia K4 LX", brand: "Kia", description: "A roomy new sedan with a digital display and advanced driver assistance.", price: 26145, image: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Subaru Impreza Convenience", brand: "Subaru", description: "A versatile hatchback with symmetrical all-wheel drive.", price: 34125, image: "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Volkswagen Jetta Trendline", brand: "Volkswagen", description: "A turbocharged sedan with a spacious cabin and heated front seats.", price: 36124, image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Chevrolet Trax LS", brand: "Chevrolet", description: "A practical compact SUV with wireless smartphone integration.", price: 28749, image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Ford Maverick XL", brand: "Ford", description: "A compact crew-cab pickup with flexible storage and modern technology.", price: 36480, image: "https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Hyundai Kona Essential", brand: "Hyundai", description: "A compact SUV with heated seats and a large digital display.", price: 29647, image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Toyota Corolla Cross L", brand: "Toyota", description: "A versatile crossover with Toyota Safety Sense and generous cargo room.", price: 33158, image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Nissan Kicks S", brand: "Nissan", description: "A city-friendly crossover with excellent visibility and modern safety features.", price: 29164, image: "https://images.unsplash.com/photo-1494905998402-395d579af36f?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Kia Seltos LX AWD", brand: "Kia", description: "An all-wheel-drive compact SUV equipped for Canadian roads.", price: 30478, image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Honda HR-V LX", brand: "Honda", description: "A comfortable crossover with flexible seating and all-wheel drive.", price: 35280, image: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Mazda CX-30 GX", brand: "Mazda", description: "A sporty compact crossover with premium interior details.", price: 30847, image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Mitsubishi RVR ES", brand: "Mitsubishi", description: "A compact all-wheel-drive SUV with a ten-year powertrain warranty.", price: 31490, image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Buick Envista Preferred", brand: "Buick", description: "A sleek crossover with a wide digital cockpit display.", price: 33820, image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Jeep Compass Sport", brand: "Jeep", description: "A capable compact SUV with four-wheel drive.", price: 37280, image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 GMC Terrain Elevation", brand: "GMC", description: "A bold compact SUV with heated seats and advanced safety features.", price: 39410, image: "https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Mini Cooper C", brand: "MINI", description: "A playful premium hatchback with an iconic circular display.", price: 34980, image: "https://images.unsplash.com/photo-1531650487048-7b6f8c0f0e99?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Volkswagen Taos Trendline", brand: "Volkswagen", description: "A turbocharged compact SUV with 4MOTION all-wheel drive.", price: 38170, image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Subaru Crosstrek Convenience", brand: "Subaru", description: "A rugged hatchback with standard all-wheel drive.", price: 36790, image: "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=1200&q=85" },
  { name: "2026 Ford Escape Active", brand: "Ford", description: "A versatile SUV with selectable drive modes and a power liftgate.", price: 38750, image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85" },
];

const ANY_NUMBER_PRIZES = [
  {name:"Premium sound system",brand:"Sony",description:"A powerful home audio system with wireless speakers.",image:"https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=85"},
  {name:"Espresso machine",brand:"Breville",description:"A stainless-steel espresso machine with a steam wand.",image:"https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=85"},
  {name:"Robot vacuum",brand:"iRobot",description:"A Wi-Fi connected robotic vacuum with smart navigation.",image:"https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=85"},
  {name:"Stand mixer",brand:"KitchenAid",description:"A colourful tilt-head stand mixer with accessories.",image:"https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?auto=format&fit=crop&w=800&q=85"},
  {name:"Patio furniture set",brand:"CANVAS",description:"A comfortable outdoor conversation set for four.",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=85"},
  {name:"Electric fireplace",brand:"Dimplex",description:"A freestanding electric fireplace with realistic flames.",image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=800&q=85"},
];

const SHELL_BONUS_PRIZES = [
  { name:"Luxury Canadian Rockies getaway",brand:"Banff Adventure",description:"A six-night mountain escape for two with airfare, a resort stay, and guided excursions.",price:7840,image:"https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=85" },
  { name:"Premium home theatre",brand:"Samsung",description:"A large OLED television, surround-sound system, and reclining theatre seats.",price:6295,image:"https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=1200&q=85" },
  { name:"Designer living room",brand:"Article",description:"A coordinated sofa, lounge chairs, coffee table, rug, and lighting package.",price:5380,image:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=85" },
  { name:"Deluxe outdoor kitchen",brand:"Napoleon",description:"A premium grill, prep island, refrigerator, and outdoor dining set.",price:8975,image:"https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=1200&q=85" },
  { name:"Electric bike package",brand:"Trek",description:"Two versatile electric bicycles with helmets, locks, and touring accessories.",price:7148,image:"https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=1200&q=85" },
  { name:"Complete bedroom suite",brand:"EQ3",description:"A king bed, premium mattress, nightstands, dresser, and upholstered bench.",price:5960,image:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=85" },
  { name:"Dream home office",brand:"Herman Miller",description:"Two ergonomic workstations with premium chairs, desks, computers, and displays.",price:9420,image:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85" },
  { name:"Caribbean cruise",brand:"Celebrity Cruises",description:"A seven-night balcony cruise for two with airfare and an onboard credit.",price:6835,image:"https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=1200&q=85" },
  { name:"Professional kitchen appliance package",brand:"KitchenAid",description:"A French-door refrigerator, range, dishwasher, and microwave.",price:8260,image:"https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1200&q=85" },
  { name:"Backyard spa retreat",brand:"Hydropool",description:"A self-cleaning hot tub with delivery, steps, cover, and patio furniture.",price:9750,image:"https://images.unsplash.com/photo-1572331165267-854da2b10ccc?auto=format&fit=crop&w=1200&q=85" },
];

const GAME_NAMES = ["plinko", "cliffHangers", "punchABunch", "diceGame", "groceryGame", "oneAway", "clockGame", "anyNumber", "grandGame", "shellGame", "moneyGame", "luckySeven", "doublePrices", "threeStrikes", "switchGame"];
const pick = (a) => a[Math.floor(Math.random() * a.length)];
const shuffle = (a) => { const c = [...a]; for (let i=c.length-1;i>0;i-=1) { const j=Math.floor(Math.random()*(i+1)); [c[i],c[j]]=[c[j],c[i]]; } return c; };
const fresh = (items, excluded=[]) => { const blocked=new Set(excluded); const unused=items.filter(x=>!blocked.has(x.name)); return unused.length ? unused : items; };
const itemCategory = (x) => x.category || (/kettle|blender|toaster|fryer|cooker|mixer|frother|skillet|steamer|waffle/i.test(x.name)?"appliance":/lamp|blanket|fire pit|weather|scale|clock/i.test(x.name)?"home":/headphone|speaker|mouse|charger|radio|camera/i.test(x.name)?"tech":/yoga|dumbbell|fitness/i.test(x.name)?"fitness":"variety");
function diverseSmallItems(count,excluded=[],predicate=()=>true,liveItems=[]){const eligibleLive=liveItems.filter(predicate),source=eligibleLive.length>=count?eligibleLive:[...eligibleLive,...SMALL_ITEMS.filter(predicate)],pool=source,available=shuffle(fresh(pool,excluded)),chosen=[],categories=new Set();for(const item of available){const category=itemCategory(item);if(categories.has(category))continue;chosen.push(item);categories.add(category);if(chosen.length===count)return chosen;}for(const item of available)if(!chosen.includes(item)){chosen.push(item);if(chosen.length===count)return chosen;}return chosen;}
const money = (n) => `$${Number(n).toLocaleString("en-CA", { maximumFractionDigits: 2 })}`;
function productVisual(p){const n=`${p?.name||""} ${p?.description||""}`.toLowerCase(),rules=[["car|sedan|suv|hatchback|pickup","🚗"],["backpack|daypack|duffel|suitcase|travel","🎒"],["camera|photo","📷"],["speaker|headphone|sound|radio|turntable","🔊"],["keyboard|computer|webcam|wi-fi|streaming|smart","💻"],["phone|charger|doorbell","📱"],["lamp|light","💡"],["clock|watch|timer","⏰"],["kettle|coffee|espresso|frother|grinder|french press","☕"],["toaster|waffle|skillet|fryer|cooker|blender|mixer|kitchen|cookware|oven|knife|bakeware|roasting","🍳"],["grill|outdoor kitchen","🔥"],["vacuum|cleaner","🧹"],["drill|tool|socket|level|multimeter|ladder|washer","🛠️"],["blanket|duvet|sheet|pillow|bedroom","🛏️"],["towel|spa|shaver|tooth|hair|skin|makeup|manicure|fragrance","🧴"],["chair|sofa|living room|furniture|rug|mirror|entryway|patio","🛋️"],["bike|bicycle","🚲"],["fitness|yoga|dumbbell|kettlebell|training|boxing|massage|balance","🏋️"],["camp|hiking|telescope|binocular|birdwatch|hammock|cooler|sleeping bag","🏕️"],["golf|pickleball|badminton|basketball","🏅"],["guitar|piano|music","🎵"],["game|lego|art|sewing|hobby","🎨"],["cruise|caribbean|rockies|getaway|trip|adventure","✈️"],["fireplace|fire pit","🔥"],["ice cream|milk|yogurt|cheese","🥛"],["cookie|cereal|granola|pancake","🥣"],["chips|wedges|pizza|tortilla","🍕"],["juice|ale|beer","🥤"],["soup|sauce|salsa|beans|tuna|mustard","🥫"],["soap|detergent|shampoo|toothpaste|tissues|paper towel|mouthwash","🧼"]];for(const [pattern,icon]of rules)if(new RegExp(pattern).test(n))return icon;return {tech:"💻",travel:"🎒",outdoors:"🏕️",cookware:"🍳",home:"🏠",tools:"🛠️",fitness:"🏋️",personal:"🧴",hobby:"🎨",appliance:"🔌"}[itemCategory(p)]||"🎁";}
const verifiedImage = (p) => Boolean(p.image && p.imageVerified!==false);
const prizeIdentity = (p) => p.id || `${String(p.brand||"prize").toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${String(p.name||"item").toLowerCase().replace(/[^a-z0-9]+/g,"-")}`;
const prizeIntro = (p) => {
  const id=prizeIdentity(p),image=verifiedImage(p)?p.image:null;
  return { id, imageKey:`${id}|${image||"no-photo"}`, name:p.name, brand:p.brand, description:p.description, image, imageAlt:p.imageAlt||p.name, visual:productVisual(p), category:itemCategory(p), imageVerified:verifiedImage(p), announcerText:`It's ${p.brand}'s ${p.name}! ${p.description}` };
};
const carIntro = (p) => ({...prizeIntro(p),visual:"🚗",announcerText:`IT'S A NEW CAR!!! ${p.description}`});

function base(type,title,player,instructions,introPrizes=[]) {
  return { type,title,playerId:player.id,playerName:player.name,instructions,introPrizes,status:"playing",result:"",winnings:0,history:[],eventSeq:0,lastOutcome:null };
}
function outcome(g, kind, text) { g.eventSeq += 1; g.lastOutcome={ kind,text,seq:g.eventSeq }; }
function holdPriceReveal(g, beforeSeq, beforeOutcome, prize, guess, actual, heldOutcome=g.lastOutcome) {
  g.eventSeq = beforeSeq;
  g.lastOutcome = beforeOutcome;
  g.priceReveal = { ...prize, guess, actual: null, correct: null };
  g._pendingPriceReveal = { actual, outcome: heldOutcome };
}
function finish(g, won, text, winnings=g.winnings) { g.status=won?"won":"lost"; g.result=text; g.winnings=winnings; g.mode="done"; g.options=[]; outcome(g,won?"win":"loss",text); }
function introduceNext(g, prize) { if (prize) g.pendingPrizeAnnouncement = prize; }
function wrongTwoDigit(actual) {
  const s=String(actual).padStart(2,"0"); const correctPosition=Math.random()<.5?0:1;
  let wrong=String(Math.floor(Math.random()*9)+1); while(wrong===s[1-correctPosition]) wrong=String(Math.floor(Math.random()*9)+1);
  const shown=correctPosition===0?s[0]+wrong:wrong+s[1];
  return { shownPrice:Number(shown), correctDigit:s[correctPosition], correctPosition };
}

function plinkoPath(start){
  let x=start+.5,velocity=0;const path=[{x,y:0,rotation:0}];
  for(let row=0;row<12;row+=1){
    const y=(row+1)/13,preferred=Math.random()<.5?-1:1;
    velocity=velocity*.28+preferred*(.34+Math.random()*.17);
    if(x<.65)velocity=Math.abs(velocity);if(x>8.35)velocity=-Math.abs(velocity);
    const impact=Math.max(.28,Math.min(8.72,x+velocity*.35));
    path.push({x:impact,y:y-.016,rotation:(row+1)*34*preferred});
    x=Math.max(.28,Math.min(8.72,x+velocity));
    path.push({x,y:y+.016,rotation:(row+1)*48*preferred});
  }
  const landing=Math.max(0,Math.min(8,Math.floor(x)));
  path.push({x:landing+.5,y:1,rotation:720});
  return {path,landing};
}

function makePlinko(player, excluded=[],liveItems=[]) {
  const q=diverseSmallItems(4,excluded,x=>x.price>=10&&x.price<100,liveItems).map(p=>({...prizeIntro(p),actual:p.price,...wrongTwoDigit(p.price)}));
  return {...base("plinko","PLINKO",player,"You get one Plinko chip free and can earn four more. For each small prize, choose the correct digit in its displayed price. Then place each chip at the top of the board and watch it bounce into one of nine cash slots. With five chips, you have a chance to win up to $50,000!",q), stage:"qualify",qualifierIndex:0,qualifiers:q.map(({actual,correctDigit,correctPosition,...x})=>x),_qualifierPrices:q.map(x=>x.actual),_qualifierCorrect:q.map(x=>x.correctDigit),chips:1,chipsLeft:0,slots:[100,500,1000,0,10000,0,1000,500,100],prompt:`You already have one free chip. Choose the correct digit in the price of the ${q[0].name} to earn another.`,mode:"choice",options:String(q[0].shownPrice).padStart(2,"0").split(""),lastDrop:null,maxPrize:50000};
}

function makePunch(player, excluded=[],liveItems=[]) {
  const prizes=diverseSmallItems(3,excluded,()=>true,liveItems); const shown=prizes.map((p,i)=>p.price+(i%2?9:-8));
  return {...base("punchABunch","PUNCH-A-BUNCH",player,"Earn up to three punches by deciding whether each small prize is higher or lower than its wrong price. Then punch the board and decide whether to keep the cash or give it back for another punch.",prizes.map(prizeIntro)),stage:"qualify",qualifierIndex:0,qualifiers:prizes.map((p,i)=>({...prizeIntro(p),shownPrice:shown[i]})),_qualifierPrices:prizes.map(p=>p.price),punches:0,punchesLeft:0,prompt:`Is the ${prizes[0].name} higher or lower than ${money(shown[0])}?`,mode:"choice",options:["Higher","Lower"],_values:shuffle([100,100,250,250,500,500,1000,1000,2500,2500,5000,5000,10000,10000,25000,50000,...Array(34).fill(0).map((_,i)=>[100,250,500,1000][i%4])]),punched:[],offer:null};
}

function diceCar(excluded=[]) { return pick(fresh(CARS.filter(c=>String(c.price).slice(1).split("").every(d=>Number(d)>=1&&Number(d)<=6)),excluded)); }
function makeDice(player,excluded=[]) {
  const car=diceCar(excluded)||CARS[2]; const digits=String(car.price).split("").map(Number);
  return {...base("diceGame","DICE GAME",player,"Roll four dice for the last four digits of the car. Exact rolls light immediately; otherwise choose higher or lower. All choices are revealed one at a time after the final roll.",[carIntro(car)]),car:prizeIntro(car),firstDigit:digits[0],_digits:digits.slice(1),rolls:[null,null,null,null],choices:[null,null,null,null],revealed:[null,null,null,null],correct:[null,null,null,null],digitIndex:0,stage:"roll",prompt:"Roll the first die.",mode:"choice",options:["Roll"],rollSeq:0};
}

function makeGrocery(player, excluded=[]) {
  const items=shuffle(fresh(GROCERIES,excluded)).slice(0,5);
  return {...base("groceryGame","GROCERY GAME",player,"Buy any quantity of each grocery item. Reach a total from $20 to $22 without going over $22.",items.map(prizeIntro)),items:items.map((x,i)=>({...prizeIntro(x),id:i,used:false})),_prices:items.map(x=>x.price),total:0,prompt:"Choose a Canadian grocery item.",mode:"choice",options:items.map((x,i)=>`${i+1}. ${x.brand} ${x.name}`),stage:"item"};
}

function makeOneAway(player,excluded=[]) {
  const car=pick(fresh(CARS,excluded)); const actual=String(car.price).split("").map(Number); const shown=actual.map(d=>d===0?1:d===9?8:d+(Math.random()<.5?-1:1));
  return {...base("oneAway","ONE AWAY",player,"Every digit shown is exactly one away from the car's true price. Choose higher or lower for each digit. If all five are right, you win immediately; otherwise you hear how many are right and may make one final correction.",[carIntro(car)]),car:prizeIntro(car),shownDigits:shown,_digits:actual,answers:[],stage:"choose",digitIndex:0,prompt:`Should the first digit be one higher or one lower than ${shown[0]}?`,mode:"choice",options:["Higher","Lower"],rightCount:null};
}

function makeCliff(player,excluded=[],liveItems=[]) { const items=diverseSmallItems(3,excluded,()=>true,liveItems); return {...base("cliffHangers","CLIFF HANGERS",player,"Price three small prizes. After each guess, the yodeling climber moves one step for every dollar you are away. Keep him from going over the cliff at step 25 to win.",items.map(prizeIntro)),items:items.map(prizeIntro),_prices:items.map(i=>i.price),itemIndex:0,climber:0,prompt:`What is the price of the ${items[0].name}?`,mode:"number",stage:"pricing",lastClimb:null}; }
function makeClock(player,excluded=[],liveItems=[]) { const items=diverseSmallItems(2,excluded,i=>i.price>=25,liveItems); return {...base("clockGame","CLOCK GAME",player,"You have 90 seconds to price two prizes. After every guess, the host tells you higher or lower.",items.map(prizeIntro)),items:items.map(prizeIntro),_prices:items.map(i=>Math.round(i.price)),itemIndex:0,_startedAt:null,_clockStarted:false,clockEndsAt:null,prompt:`Guess the price of the ${items[0].name}.`,mode:"number",clue:"90 seconds starts now!",secondsLeft:90}; }
function makeAnyNumber(player,excluded=[]) { const compatible=fresh(CARS.filter(c=>{const d=String(c.price).split("").map(Number);return new Set(d).size===5;}),excluded), carPrize=pick(compatible), car=String(carPrize.price).split("").map(Number), remaining=shuffle([0,1,2,3,4,5,6,7,8,9].filter(d=>!car.includes(d))), small=remaining.slice(0,3), pig=remaining.slice(3,5), secondaryBase=pick(fresh(ANY_NUMBER_PRIZES,excluded)), secondary={...secondaryBase,price:Number(small.join(""))}; return {...base("anyNumber","ANY NUMBER",player,"Call digits one at a time. You win whichever price you completely reveal first: the car, the three-digit prize, or the money in the piggy bank.",[carIntro(carPrize),prizeIntro(secondary)]),car:prizeIntro(carPrize),secondaryPrize:prizeIntro(secondary),boards:[{label:"Car",cells:[car[0],null,null,null,null]},{label:secondary.name,cells:[null,null,null]},{label:"Piggy Bank",cells:[null,null]}],_answers:[car,small,pig],usedDigits:[car[0]],prompt:"Choose a digit.",mode:"choice",options:[0,1,2,3,4,5,6,7,8,9].filter(d=>d!==car[0]).map(String)}; }
function makeGrand(player,excluded=[]) { const available=fresh(GROCERIES,excluded), target=6, cheap=shuffle(available.filter(i=>i.price<target)).slice(0,4), pricey=shuffle(available.filter(i=>i.price>=target)).slice(0,2), items=shuffle([...cheap,...pricey]); return {...base("grandGame","GRAND GAME",player,"Pick the four products priced below the target. Each correct pick multiplies your money by ten.",items.map(prizeIntro)),target,items:items.map(i=>({...prizeIntro(i),selected:false})),_prices:items.map(i=>i.price),prompt:`Pick a product under ${money(target)}.`,mode:"choice",options:items.map((i,n)=>`${n+1}. ${i.name}`),correct:0,winnings:1}; }
function makeShell(player,excluded=[],liveItems=[]) { const items=diverseSmallItems(4,excluded,()=>true,liveItems), shown=items.map((x,i)=>x.price+(i%2?-8:9)), bonus=pick(fresh(SHELL_BONUS_PRIZES,excluded)),bonusPrize={...prizeIntro(bonus),announcerText:`You could win this spectacular grand prize: ${bonus.description}`}; return {...base("shellGame","SHELL GAME",player,"Price four small prizes. Every correct higher-or-lower decision wins that prize and earns a marker for one shell. Then choose from the shells you earned. Find the hidden ball to win the grand prize. Earn all four shells and the grand prize is guaranteed.",[bonusPrize,...items.map(prizeIntro)]),bonusPrize,_bonusPrice:bonus.price,items:items.map((x,i)=>({...prizeIntro(x),shownPrice:shown[i]})),_prices:items.map(i=>i.price),itemIndex:0,shells:0,wonSmallValue:0,_ball:Math.floor(Math.random()*4),chosenShells:[],prompt:`${items[0].name}: higher or lower than ${money(shown[0])}?`,mode:"choice",options:["Higher","Lower"],stage:"prices"}; }

function makeMoneyGame(player,excluded=[]) { const car=pick(fresh(CARS,excluded)),digits=String(car.price),front=digits.slice(0,2),middleDigit=Number(digits[2]),back=digits.slice(-2),decoys=new Set([front,back]);while(decoys.size<9)decoys.add(String(10+Math.floor(Math.random()*90)));const options=shuffle([...decoys]);return {...base("moneyGame","MONEY GAME",player,"The middle digit in the car's five-digit price is free. Pick the first two digits and the last two digits. Wrong choices go on your cash line; four wrong choices end the game.",[carIntro(car)]),car:prizeIntro(car),middleDigit,_digits:digits.split("").map(Number),_front:front,_back:back,frontFound:false,backFound:false,cash:0,wrong:[],choices:options,prompt:"Pick a number pair.",mode:"choice",options}; }
function makeLuckySeven(player,excluded=[]) { const car=pick(fresh(CARS,excluded)),digits=String(car.price).split("").map(Number);return {...base("luckySeven","LUCKY SEVEN",player,"The first digit is free. Guess each remaining digit; you lose one dollar for every number you are away. Keep at least one of your seven dollars to buy the car.",[carIntro(car)]),car:prizeIntro(car),_digits:digits,revealed:[digits[0],null,null,null,null],digitIndex:1,dollars:7,prompt:"Guess the second digit.",mode:"choice",options:Array.from({length:10},(_,i)=>String(i))}; }
function makeDoublePrices(player,excluded=[]){const raw=pick(fresh(SHELL_BONUS_PRIZES,excluded)),prize=prizeIntro(raw),wrong=raw.price+pick([650,800,950,1200]),options=shuffle([raw.price,wrong]);return {...base("doublePrices","DOUBLE PRICES",player,"The grand prize has two possible prices. Choose the correct price to win it.",[prize]),prize,_actual:raw.price,prices:options,prompt:"Which is the correct price?",mode:"choice",options:options.map(money)};}
function makeThreeStrikes(player,excluded=[]){const compatible=fresh(CARS.filter(car=>new Set(String(car.price)).size===5),excluded),raw=pick(compatible),digits=String(raw.price).split("").map(Number),car=prizeIntro(raw),bag=[...digits,"X1","X2","X3"];return {...base("threeStrikes","3 STRIKES",player,"Five numbered balls—one for each digit in the car price—and three strike balls are mixed in the hopper. Draw a ball. Place a number in its correct position to remove it; a wrong placement returns it to the hopper. Place all five digits before drawing three strikes to win the car.",[carIntro(raw)]),car,_digits:digits,_bag:shuffle(bag),revealed:[null,null,null,null,null],strikes:0,currentBall:null,drawSeq:0,stage:"draw",prompt:"Draw a ball from the hopper.",mode:"choice",options:["DRAW A BALL"]};}
function makeSwitch(player,excluded=[]){const raw=shuffle(fresh(SHELL_BONUS_PRIZES,excluded)).slice(0,2),items=raw.map(prizeIntro),actual=raw.map(p=>p.price),shown=Math.random()<.5?actual:[actual[1],actual[0]];return {...base("switchGame","SWITCH?",player,"The two prize prices may already be correct, or they may be switched. Leave the prices where they are or switch them to win both prizes.",items),items,_prices:actual,shownPrices:shown,prompt:"Should the prices stay, or should they switch?",mode:"choice",options:["Leave them","Switch them"]};}

const FACTORIES={plinko:makePlinko,cliffHangers:makeCliff,punchABunch:makePunch,diceGame:makeDice,groceryGame:makeGrocery,oneAway:makeOneAway,clockGame:makeClock,anyNumber:makeAnyNumber,grandGame:makeGrand,shellGame:makeShell,moneyGame:makeMoneyGame,luckySeven:makeLuckySeven,doublePrices:makeDoublePrices,threeStrikes:makeThreeStrikes,switchGame:makeSwitch};
export const PRICING_GAME_TYPES=[...GAME_NAMES];
export function createPricingGameForType(type,player,excluded=[],liveItems=[]){ if(!FACTORIES[type]) throw new Error(`Unknown pricing game: ${type}`); return FACTORIES[type](player,excluded,liveItems); }
export function createPricingGame(player,previous=[],excluded=[],liveItems=[]){ const a=GAME_NAMES.filter(x=>!previous.includes(x)); return FACTORIES[pick(a.length?a:GAME_NAMES)](player,excluded,liveItems); }
export function pricingPrizeNames(game){return [...(game?.qualifiers||[]),...(game?.items||[]),...(game?.introPrizes||[])].map(x=>x?.name).filter(Boolean);}

export function playPricingGame(g,action={}) {
  if(!g||g.status!=="playing") throw new Error("Pricing game is not active"); const choice=String(action.choice??""); const value=Math.round(Number(action.value));
  if(g.type==="plinko") {
    if(g.stage==="qualify") { const beforeSeq=g.eventSeq,beforeOutcome=g.lastOutcome,i=g.qualifierIndex, q=g.qualifiers[i], correct=choice===g._qualifierCorrect[i]; if(correct){g.chips+=1;g.history.push(`${q.name}: ${money(g._qualifierPrices[i])} — correct! You won the prize and a chip.`);outcome(g,"success","Correct — another Plinko chip!");}else{g.history.push(`${q.name}: the correct digit was ${g._qualifierCorrect[i]}.`);outcome(g,"failure","That digit was not correct.");} g.qualifierIndex+=1; if(g.qualifierIndex===g.qualifiers.length){g.stage="drop";g.chipsLeft=g.chips;g.mode="drop";g.options=[];g.prompt=`Tap one of the nine drop positions for chip 1 of ${g.chips}.`;}else{const n=g.qualifiers[g.qualifierIndex];g.options=String(n.shownPrice).padStart(2,"0").split("");g.prompt=`Choose the correct digit in the price of the ${n.name}.`;introduceNext(g,n);} holdPriceReveal(g,beforeSeq,beforeOutcome,q,choice,g._qualifierPrices[i]); }
    else if(g.stage==="drop") { const start=Math.max(0,Math.min(8,Number(action.position??choice)-1)),simulation=plinkoPath(start);g.stage="dropping";g.mode="wait";g.lastDrop={id:(g.lastDrop?.id||0)+1,start,...simulation,duration:5600};g.prompt="The chip is falling…"; }
  } else if(g.type==="punchABunch") {
    if(g.stage==="qualify") { const beforeSeq=g.eventSeq,beforeOutcome=g.lastOutcome,i=g.qualifierIndex, actual=g._qualifierPrices[i], shown=g.qualifiers[i].shownPrice, correct=choice.toLowerCase()===(actual>shown?"higher":"lower"); if(correct){g.punches+=1;outcome(g,"success","Correct — you earned a punch!");}else outcome(g,"failure","No punch for that prize.");const revealOutcome=g.lastOutcome;g.history.push(`${g.qualifiers[i].name}: ${money(actual)} — ${correct?"correct":"incorrect"}.`);g.qualifierIndex+=1;if(g.qualifierIndex===3){if(!g.punches)finish(g,false,"No punches were earned.");else{g.punchesLeft=g.punches;g.stage="punch";g.options=Array.from({length:50},(_,n)=>String(n+1));g.prompt=`You earned ${g.punches} punch${g.punches===1?"":"es"}. Pick a hole.`;}}else{const n=g.qualifiers[g.qualifierIndex];g.prompt=`Is the ${n.name} higher or lower than ${money(n.shownPrice)}?`;introduceNext(g,n);} holdPriceReveal(g,beforeSeq,beforeOutcome,g.qualifiers[i],choice,actual,revealOutcome); }
    else if(g.stage==="punch") { const i=Math.max(0,Math.min(49,Number(choice)-1));if(g.punched.includes(i))throw new Error("That hole has already been punched");g.punched.push(i);g.punchesLeft-=1;g.offer=g._values[i];g.winnings=g.offer;g.history.push(`Hole ${i+1} held ${money(g.offer)}.`);outcome(g,"success",`You found ${money(g.offer)}!`);if(!g.punchesLeft)finish(g,true,`Your final punch is worth ${money(g.offer)}!`,g.offer);else{g.stage="decision";g.options=["Keep it","Punch again"];g.prompt=`You found ${money(g.offer)}. Keep it, or give it back for another punch?`;} }
    else if(choice.toLowerCase().startsWith("keep"))finish(g,true,`You kept ${money(g.offer)}!`,g.offer);else{g.stage="punch";g.options=Array.from({length:50},(_,n)=>g.punched.includes(n)?null:String(n+1)).filter(Boolean);g.prompt=`Pick another hole. ${g.punchesLeft} punch${g.punchesLeft===1?"":"es"} left.`;}
  } else if(g.type==="diceGame") {
    if(g.stage==="roll") { const i=g.digitIndex, roll=1+Math.floor(Math.random()*6);g.rolls[i]=roll;g.rollSeq+=1;if(roll===g._digits[i]){g.choices[i]="Exact";g.revealed[i]=roll;g.correct[i]=true;outcome(g,"success",`A ${roll} — exactly right!`);g.digitIndex+=1;}else{g.stage="direction";g.prompt=`The die shows ${roll}. Is the hidden digit higher or lower?`;g.options=roll===1?["Higher"]:roll===6?["Lower"]:["Higher","Lower"];return g;} }
    else if(g.stage==="direction"){g.choices[g.digitIndex]=choice;g.digitIndex+=1;g.stage="roll";outcome(g,"neutral","Choice locked in. No result yet.");}
    else { const i=g.revealIndex, target=g._digits[i], roll=g.rolls[i], exact=g.choices[i]==="Exact", correct=exact||g.choices[i].toLowerCase()===(target>roll?"higher":"lower");g.revealed[i]=target;g.correct[i]=correct;g.revealIndex+=1;outcome(g,correct?"success":"failure",`Digit ${i+2} is ${target}: ${correct?"correct":"incorrect"}.`);if(g.revealIndex===4){const won=g.correct.every(Boolean);finish(g,won,won?`You won the ${g.car.name}!`:"The car price was not completed.");}else g.prompt="Reveal the next digit.";return g; }
    if(g.digitIndex===4){g.stage="reveal";g.revealIndex=0;g.prompt="All choices are locked. Reveal the first digit.";g.options=["Reveal next digit"];}
    else if(g.stage==="roll"){g.prompt=`Roll die ${g.digitIndex+1}.`;g.options=["Roll"];}
  } else if(g.type==="groceryGame") {
    if(g.stage==="item"){const i=Number(choice.split(".")[0])-1;if(g.items[i]?.used)throw new Error("That item was already used");g.selected=i;g.stage="quantity";g.mode="number";g.prompt=`How many ${g.items[i].brand} ${g.items[i].name} would you like?`;}
    else{const qty=Math.max(1,Math.min(20,value)),i=g.selected,add=Number((g._prices[i]*qty).toFixed(2));g.total=Number((g.total+add).toFixed(2));g.items[i].used=true;g.history.push(`${qty} × ${g.items[i].name} = ${money(add)}; total ${money(g.total)}.`);outcome(g,g.total<=22?"success":"failure",`Your total is now ${money(g.total)}.`);if(g.total>=20&&g.total<=22)finish(g,true,`Perfect shopping! Your total is ${money(g.total)}.`);else if(g.total>22||g.items.every(x=>x.used))finish(g,false,`Your final total is ${money(g.total)}.`);else{g.stage="item";g.mode="choice";g.options=g.items.map((x,n)=>x.used?null:`${n+1}. ${x.brand} ${x.name}`).filter(Boolean);g.prompt="Choose another item.";}}
  } else if(g.type==="oneAway") {
    if(g.stage==="choose"){g.answers[g.digitIndex]=choice;g.digitIndex+=1;if(g.digitIndex===5){const proposed=g.shownDigits.map((d,i)=>d+(g.answers[i].toLowerCase()==="higher"?1:-1));g.rightCount=proposed.filter((d,i)=>d===g._digits[i]).length;if(g.rightCount===5)return finish(g,true,`ALL FIVE DIGITS ARE RIGHT! You won the ${g.car.name}!`);outcome(g,g.rightCount?"success":"failure",`${g.rightCount} digit${g.rightCount===1?" is":"s are"} right.`);if(!g.rightCount)return finish(g,false,"Not one digit was right.");g.stage="revise";g.mode="multi";g.options=[];g.prompt=`You have ${g.rightCount} right. Submit your final higher/lower choices.`;}else g.prompt=`Should digit ${g.digitIndex+1} be one higher or lower than ${g.shownDigits[g.digitIndex]}?`;}
    else{const answers=Array.isArray(action.answers)?action.answers:g.answers;const final=g.shownDigits.map((d,i)=>d+(String(answers[i]).toLowerCase()==="higher"?1:-1));const won=final.every((d,i)=>d===g._digits[i]);finish(g,won,won?`You won the ${g.car.name}!`:`The actual price was ${money(Number(g._digits.join("")))}.`);}
  } else if(g.type==="cliffHangers") {if(g.stage!=="pricing")throw new Error("Wait for the climber to stop");if(!Number.isFinite(value))throw new Error("Enter a price");const i=g.itemIndex,actual=g._prices[i],error=Math.abs(value-actual),from=g.climber,to=from+error;g.climber=to;g.stage="climbing";g.mode="wait";g.lastClimb={id:(g.lastClimb?.id||0)+1,from,to,duration:Math.max(1200,Math.min(22500,error*900)),stepDuration:900};g._pendingCliffReveal={i,guess:value,actual,error,beforeSeq:g.eventSeq,beforeOutcome:g.lastOutcome};g.prompt=error===0?"Will the climber move?":"Here he goes! Watch the climber...";
  } else if(g.type==="clockGame") {g.secondsLeft=Math.max(0,Math.ceil(((g.clockEndsAt||g._startedAt+90000)-Date.now())/1000));if(!g.secondsLeft)return finish(g,false,"Time is up!");const actual=Math.round(g._prices[g.itemIndex]);if(value===actual){outcome(g,"success","Correct!");g.itemIndex+=1;if(g.itemIndex===2)return finish(g,true,`Both prizes won with ${g.secondsLeft} seconds left!`);g.prompt=`Now price the ${g.items[1].name}.`;introduceNext(g,g.items[1]);}else{g.clue=actual>value?"Higher!":"Lower!";g.prompt=`${g.clue} ${g.secondsLeft} seconds left.`;}
  } else if(g.type==="anyNumber") {const d=Number(choice);if(g.usedDigits.includes(d))throw new Error("Digit already chosen");g.usedDigits.push(d);g.options=g.options.filter(x=>Number(x)!==d);for(let b=0;b<g._answers.length;b++)for(let c=0;c<g._answers[b].length;c++)if(g._answers[b][c]===d)g.boards[b].cells[c]=d;const done=g.boards.findIndex(b=>b.cells.every(x=>x!==null));if(done>=0)finish(g,done===0,`You completed the ${g.boards[done].label} price!`);
  } else if(g.type==="grandGame") {const i=Number(choice.split(".")[0])-1;if(g.items[i]?.selected)throw new Error("Already selected");g.items[i].selected=true;const actual=g._prices[i];g.history.push(`${g.items[i].name}: ${money(actual)}.`);if(actual>=g.target)finish(g,false,`That item was not below ${money(g.target)}.`);else{g.correct+=1;g.winnings*=10;outcome(g,"success","Correct!");if(g.correct===4)finish(g,true,"Four correct products — you won $10,000!",10000);else{g.options=g.items.map((x,n)=>x.selected?null:`${n+1}. ${x.name}`).filter(Boolean);g.prompt="Pick another product.";}}
  } else if(g.type==="shellGame") {if(g.stage==="prices"){const beforeSeq=g.eventSeq,beforeOutcome=g.lastOutcome,i=g.itemIndex,correct=choice.toLowerCase()===(g._prices[i]>g.items[i].shownPrice?"higher":"lower");if(correct){g.shells+=1;g.wonSmallValue+=g._prices[i];}outcome(g,correct?"success":"failure",correct?"Correct — you won the small prize and earned a shell marker!":"Incorrect.");const revealOutcome=g.lastOutcome;g.itemIndex+=1;if(g.itemIndex===4){if(!g.shells)finish(g,false,"No shell markers were earned.",0);else if(g.shells===4){g.stage="complete";g.mainPrizeWon=true;g.revealedBall=g._ball+1;finish(g,true,`All four shell markers! You automatically win the ${g.bonusPrize.name}!`,g.wonSmallValue+g._bonusPrice);}else{g.options=["1","2","3","4"];g.stage="shell";g.prompt=`You earned ${g.shells} shell marker${g.shells===1?"":"s"}. Pick a shell.`;}}else{g.prompt=`${g.items[g.itemIndex].name}: higher or lower than ${money(g.items[g.itemIndex].shownPrice)}?`;introduceNext(g,g.items[g.itemIndex]);}holdPriceReveal(g,beforeSeq,beforeOutcome,g.items[i],choice,g._prices[i],revealOutcome);}else{const selected=Number(choice);if(g.chosenShells.includes(selected))throw new Error("That shell was already chosen");g.chosenShells.push(selected);const hit=selected-1===g._ball;g.shells-=1;if(hit){g.revealedBall=g._ball+1;g.mainPrizeWon=true;finish(g,true,`Lift it up... the ball is under shell ${choice}! You won the ${g.bonusPrize.name}!`,g.wonSmallValue+g._bonusPrice);}else if(!g.shells){g.revealedBall=g._ball+1;finish(g,false,`Let's lift the shells. The ball was under shell ${g._ball+1}. You keep the small prizes you priced correctly.`,g.wonSmallValue);}else{g.options=g.options.filter(x=>Number(x)!==selected);g.prompt="Pick another shell.";}}}
  else if(g.type==="moneyGame"){if(!g.options.includes(choice))throw new Error("That number is not available");g.options=g.options.filter(x=>x!==choice);if(choice===g._front){g.frontFound=true;g.frontValue=choice;}else if(choice===g._back){g.backFound=true;g.backValue=choice;}else{g.wrong.push(choice);g.cash+=Number(choice);}if(g.frontFound&&g.backFound)finish(g,true,`You completed the price and won the ${g.car.name}!`);else if(g.wrong.length===4)finish(g,false,`Four wrong choices. You won ${money(g.cash)}, but not the car.`);else{outcome(g,choice===g._front||choice===g._back?"success":"failure",choice===g._front||choice===g._back?"That's part of the car price!":`${money(Number(choice))} goes on your cash line.`);g.prompt="Pick another number pair.";}}
  else if(g.type==="luckySeven"){const guess=Math.max(0,Math.min(9,Number(choice))),actual=g._digits[g.digitIndex],cost=Math.abs(guess-actual);g.dollars-=cost;g.revealed[g.digitIndex]=actual;g.history.push(`You guessed ${guess}; the digit was ${actual}. Cost: $${cost}.`);g.digitIndex+=1;if(g.dollars<1)return finish(g,false,"You ran out of dollars before completing the car price.");if(g.digitIndex===5)return finish(g,true,`You have $${g.dollars} left—pay one dollar and the ${g.car.name} is yours!`);outcome(g,cost===0?"success":"neutral",cost===0?"Exactly right!":`That costs $${cost}. You have $${g.dollars} left.`);g.prompt=`Guess digit ${g.digitIndex+1}.`;}
  else if(g.type==="doublePrices"){const selected=Number(choice.replace(/[$,]/g,"")),won=selected===g._actual;g.revealedPrice=g._actual;finish(g,won,won?`That's the correct price! You won the ${g.prize.name}!`:`The actual retail price was ${money(g._actual)}.`,won?g._actual:0);}
  else if(g.type==="threeStrikes"){if(g.stage==="draw"){const index=Math.floor(Math.random()*g._bag.length),ball=g._bag.splice(index,1)[0];g.currentBall=String(ball).startsWith("X")?"X":Number(ball);g.drawSeq+=1;if(g.currentBall==="X"){g.strikes+=1;outcome(g,"failure",`Strike ${g.strikes}!`);if(g.strikes===3)return finish(g,false,`Strike three! The car's actual retail price was ${money(Number(g._digits.join("")))}.`);g.prompt="Draw another ball from the hopper.";g.options=["DRAW ANOTHER BALL"];}else{g.stage="place";g.prompt=`You drew the number ${g.currentBall}. Where does it belong in the car price?`;g.options=g.revealed.map((digit,i)=>digit==null?`Position ${i+1}`:null).filter(Boolean);}}else{const position=Number(choice.match(/\d+/)?.[0])-1,digit=g.currentBall;if(g._digits[position]===digit){g.revealed[position]=digit;outcome(g,"success",`${digit} belongs in position ${position+1}!`);if(g.revealed.every(x=>x!=null))return finish(g,true,`You completed the price and won the ${g.car.name}!`,Number(g._digits.join("")));}else{g._bag.push(digit);outcome(g,"failure",`${digit} does not belong in position ${position+1}. Back into the hopper!`);}g.currentBall=null;g.stage="draw";g.prompt="Draw another ball from the hopper.";g.options=["DRAW ANOTHER BALL"];}}
  else if(g.type==="switchGame"){const selected=choice==="Switch them"?[g.shownPrices[1],g.shownPrices[0]]:g.shownPrices,won=selected.every((price,i)=>price===g._prices[i]);g.finalPrices=g._prices;finish(g,won,won?"The prices are right! You won both prizes!":`The correct prices were ${money(g._prices[0])} and ${money(g._prices[1])}.`,won?g._prices.reduce((a,b)=>a+b,0):0);}
  return g;
}

export function publicPricingGame(game){if(!game)return null;return Object.fromEntries(Object.entries(game).filter(([k])=>!k.startsWith("_")));}

export function syncClockGame(game,now=Date.now()){
  if(game?.type!=="clockGame"||game.status!=="playing"||!game.clockEndsAt)return false;
  game.secondsLeft=Math.max(0,Math.ceil((game.clockEndsAt-now)/1000));
  if(game.secondsLeft)return false;
  game.timeoutPrice=game._prices[game.itemIndex];
  finish(game,false,"Time is up!");
  return true;
}

export function revealDeferredPrice(game) {
  if (!game?._pendingPriceReveal || !game.priceReveal) throw new Error("No price is waiting to be revealed");
  const pending=game._pendingPriceReveal;
  game.priceReveal.actual=pending.actual;
  game.priceReveal.correct=pending.outcome?.kind === "success" || pending.outcome?.kind === "win";
  if (pending.outcome) outcome(game,pending.outcome.kind,pending.outcome.text);
  return game;
}

export function clearDeferredPrice(game) {
  if (!game?._pendingPriceReveal) throw new Error("No revealed price is waiting");
  game.priceReveal=null;
  game._pendingPriceReveal=null;
  return game;
}

export function initialPrizeAnnouncements(game) {
  if (!game) return [];
  if (game.type === "plinko" || game.type === "punchABunch") return [game.qualifiers[0]];
  if (game.type === "shellGame") return [game.bonusPrize, game.items[0]];
  if (game.type === "cliffHangers" || game.type === "clockGame") return [game.items[0]];
  return game.introPrizes || [];
}

export function settlePricingAnimation(game) {
  if(game?.type==="cliffHangers"){
    if(game.stage!=="climbing"||!game._pendingCliffReveal)throw new Error("The climber is not moving");const p=game._pendingCliffReveal;game.history.push(`${game.items[p.i].name}: ${money(p.guess)}, actual ${money(p.actual)} — ${p.error} steps.`);outcome(game,p.error===0?"success":"failure",p.error===0?"Exactly right!":`${p.error} climber step${p.error===1?"":"s"}.`);const revealOutcome=game.lastOutcome;game.itemIndex+=1;game.stage="pricing";game.mode="number";if(game.climber>25){game.cliffOver=true;finish(game,false,"The climber went over the cliff!");}else if(game.itemIndex===3){game.cliffFinalWin=true;finish(game,true,`HE MADE IT! You won all three prizes!`,game._prices.reduce((sum,price)=>sum+price,0));}else{game.prompt=`What is the price of the ${game.items[game.itemIndex].name}?`;introduceNext(game,game.items[game.itemIndex]);}holdPriceReveal(game,p.beforeSeq,p.beforeOutcome,game.items[p.i],money(p.guess),p.actual,revealOutcome);game._pendingCliffReveal=null;return game;
  }
  if (game?.type !== "plinko" || game.stage !== "dropping" || !game.lastDrop) throw new Error("No pricing-game animation is active");
  const won=game.slots[game.lastDrop.landing];game.lastDrop.value=won;game.winnings+=won;game.chipsLeft-=1;game.history.push(`Chip landed in ${money(won)}.`);game.stage="drop";game.mode="drop";outcome(game,won?"success":"failure",`The chip landed on ${money(won)}.`);
  if(!game.chipsLeft)finish(game,game.winnings>0,`You won ${money(game.winnings)} on Plinko!`);else game.prompt=`Tap a drop position for your next chip. ${game.chipsLeft} remaining.`;
  return game;
}
